### ISSUE TITLE
firehose_exporter internal server error 500

### ISSUE THREAD

**Issue by scult** [bosh-prometheus/firehose_exporter#20]
Hi, we are using the prometheus bosh release and we've found an issue with the firehose exporter related to issue #13. When a user has two queues in one vhost with the same name but once using "-" and once using "_" the firehose exporter returns a 500 internal server error upon scraping similar to #13.

This is the error message we get (anonymized):

6 error(s) occurred:
* collected metric firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_GUID_example_queue_consumers label:<name:"bosh_deployment" value:"cf-rabbitmq" > label:<name:"bosh_job_id" value:”xxxxxx” > label:<name:"bosh_job_ip" value:”xxxxx” > label:<name:"bosh_job_name" value:"rabbitmq-server" > label:<name:"environment" value:"TEST" > label:<name:"origin" value:"p-rabbitmq" > label:<name:"unit" value:"count" > gauge:<value:3 >  has help "Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/GUID/test-queue/consumers' value metric from 'p-rabbitmq'." but should have "Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/GUID/test_queue/consumers' value metric from 'p-rabbitmq'."

From the other ticket I gathered that this might be hard to fix, but this is an issue that's not really preventable from an operators point of view for a platform with a large number of users and vhosts. 

For reference we are using version 4.2.3 of the firehose exporter.

Can you please take a look at the issue?

Regards,
Daniel

**Comment by frodenas** [comment]
From @jigsheth57 at https://github.com/bosh-prometheus/firehose_exporter/issues/21:

exporter throws error, when RMQ ODB instance are created. It's preventing scrape of other metrics and shows State as "DOWN".

$ curl http://10.193.177.96:9186/metrics
An error has occurred during metrics collection:

67 error(s) occurred:
* collected metric firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_pending label:<name:"bosh_deployment" value:"cf-rabbitmq" > label:<name:"bosh_job_id" value:"4e1f863c-236d-4bb2-ae44-48e221aacd7f" > label:<name:"bosh_job_ip" value:"10.193.177.118" > label:<name:"bosh_job_name" value:"rabbitmq-server" > label:<name:"environment" value:"cf" > label:<name:"origin" value:"p-rabbitmq" > label:<name:"unit" value:"count" > gauge:<value:0 >  has help "Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/messages/pending' value metric from 'p-rabbitmq'." but should have "Cloud Foundry Firehose '/p.rabbitmq/rabbitmq/messages/pending' value metric from 'p-rabbitmq'."


In RabbitMQ ODB service, the valueMetric.Origin will be presented as "p.rabbitmq" while the share service instance would be presented as "p-rabbitmq". Somewhere in the exporter, this is being compare and throws exception as it was expecting the metric path to be same as deployment "p-rabbitmq"

**Comment by frodenas** [comment]
Apologies, I was too fast relating the two issues, seems different to now that I'm taking a closer look.

@jigsheth57 What version of the `firehose_exporter` are you using?
@scult As #13, it's an easy fix if I break existing deployments, let me think if I can find a workaround.

**Comment by frodenas** [comment]
This has been fixed at [v4.2.7](https://github.com/bosh-prometheus/firehose_exporter/releases/tag/v4.2.7).
