### ISSUE TITLE
server returned HTTP status 500 Internal Server Error

### ISSUE THREAD

**Issue by jigsheth57** [bosh-prometheus/firehose_exporter#21]
exporter throws error, when RMQ ODB instance are created. It's preventing scrape of other metrics and shows State as "DOWN".

$ curl http://10.193.177.96:9186/metrics
An error has occurred during metrics collection:

67 error(s) occurred:
* collected metric firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_messages_pending label:<name:"bosh_deployment" value:"cf-rabbitmq" > label:<name:"bosh_job_id" value:"4e1f863c-236d-4bb2-ae44-48e221aacd7f" > label:<name:"bosh_job_ip" value:"10.193.177.118" > label:<name:"bosh_job_name" value:"rabbitmq-server" > label:<name:"environment" value:"cf" > label:<name:"origin" value:"p-rabbitmq" > label:<name:"unit" value:"count" > gauge:<value:0 >  has help "Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/messages/pending' value metric from 'p-rabbitmq'." but should have "Cloud Foundry Firehose '/p.rabbitmq/rabbitmq/messages/pending' value metric from 'p-rabbitmq'."

In RabbitMQ ODB service, the valueMetric.Origin will be presented as "p.rabbitmq" while the share service instance would be presented as "p-rabbitmq". Somewhere in the exporter, this is being compare and throws exception as it was expecting the metric path to be same as deployment "p-rabbitmq"

**Comment by frodenas** [comment]
Tracking this at https://github.com/bosh-prometheus/firehose_exporter/issues/20.
