### ISSUE TITLE
p-mysql Scrape Bug 

### ISSUE THREAD

**Issue by abelnbcuni** [bosh-prometheus/firehose_exporter#23]
Not sure if this is a duplicate of the already open issue (#20 ) but i attempted to install this exporter on PCF v 1.11. When i navigate to http://<firehose-vm-IP>:9186/metrics. I get this message

87 error(s) occurred: (I just included the first message)
* collected metric firehose_value_metric_p_mysql_p_mysql_performance_table_locks_waited label:<name:"bosh_deployment" value:"service-instance_effb449c-c681-48c8-b816-e7dd4dec7796" > label:<name:"bosh_job_id" value:"452326b5-3899-4445-96dd-7f537f5fdac8" > label:<name:"bosh_job_ip" value:"<mysql-ip>" > label:<name:"bosh_job_name" value:"<mysql-ip>" > label:<name:"environment" value:"cf" > label:<name:"origin" value:"p.mysql" > label:<name:"unit" value:"number" > gauge:<value:0 >  has help "Cloud Foundry Firehose '/p.mysql/performance/table_locks_waited' value metric from 'p-mysql'." but should have "Cloud Foundry Firehose '/p-mysql/performance/table_locks_waited' value metric from 'p-mysql'." 

I believe this prevents the scrape from happening. Asking around on the prometheus IRC got this result

"for the Go client all the ConstMetrics need to have the same help sting" if that is of any help

**Comment by frodenas** [comment]
What tile have you installed? `MySQL for PCF ` or `MySQL for PCF v2`?

**Comment by abelnbcuni** [comment]
We have both installed on the foundation. But the IP address listed by the error is for MySQL For PCF v 1.10.5 Tile.

**Comment by frodenas** [comment]
Thanks @abelnbcuni. When both tiles are installed, there's a mismatch between the metric names (one reports them as `/p-mysql/` and the other as `/p.mysql/`.

This has been fixed at [v4.2.7](https://github.com/bosh-prometheus/firehose_exporter/releases/tag/v4.2.7).

**Comment by abelnbcuni** [comment]
Thanks @frodenas for addressing this so quickly. Have a great Holiday!
