### ISSUE TITLE
Delay in metrics appearing in exporter

### ISSUE THREAD

**Issue by andrewghobrial** [bosh-prometheus/firehose_exporter#30]
Hi,

I have noticed that sometimes that there is a delay from when metrics are returned by the firehose exporter compared to when they appear from the firehose running "cf nozzle". Is there a reason for this delay? It's most noticeable when the exporter is first started, because the metrics are totally missing until a while after.

For example, the rep CapacityTotalMemory is emitted every 60 seconds from Firehose, but there is usually a delay of more than 60 seconds until the metric is shown by the exporter.

What is the reason for this?

**Comment by frodenas** [comment]
Where did you notice the delay? When hitting the `/metrics` endpoint at the `firehose_exporter` or looking at the prometheus/grafana console?

For the former, there should NOT be any delay, as-as soon as the nozzle receives the metric, it stores it, so hitting the endpoint should return the metric.

For the latter, the `scrape_interval` set at the prometheus bosh release affects how prometheus scrapes the `firehose_exporter`. By default is `1m`, this means that in the worst case scenario (and using that default), it can take 60seconds to show up at prometheus.

w/r/t that is more noticeable when it's started, I'm assuming here that you notice this at the prometheus/grafana console. This may happen when prometheus uses the file service discovery approach. The `bosh_exporter` is configured to be scrapped every `2m`, and the service discovery file is not created until the 1st scrappe. When prometheus finds that file (after `2m` when hitting the `bosh_exporter` endpoint), prometheus will detect a `firehose_exporter`, and then it will start scrapping it after `1m`. So to summarize, it may take at least `3m` when prometheus is started to start showing metrics from prometheus.

Hope this clarifies your question.

**Comment by andrewghobrial** [comment]
Thanks for quick reply. I am in fact talking about the /metrics endpoint.

I pulled the project locally and started digging into the code. I noticed that when I replaced 	`n.messages, n.errs = n.consumer.FilteredFirehose(n.subscriptionID, "", consumer.Metrics)`
in consumeFirehose() function with 

`	n.messages, n.errs = n.consumer.Firehose(n.subscriptionID, "")
`
that the metrics DID come in immediately. I figured that means this a bug with noaa. However, I pulled in the latest noaa project, and used their firehose sample project on the same CF Firehose wss. I was able to get the metrics immediately on time regarless if I used any of those two lines of code quoted above. 

I am currently investigating the difference between running the FilteredFirehose function in the exporter versus the sample firehose application. I have double checked that I am accessing the same noaa project by putting a print statement that displays when running either the exporter or the sample project... (I had to remove the vendored noaa and used the one installed in my GO path to test this)

**Comment by frodenas** [comment]
@andrewghobrial Interesting, please keep me posted.

**Comment by andrewghobrial** [comment]
@frodenas So my problem is that I had multiple firehose exporter instances accessing the same firehose with the same subscription id (using the default environment var value "prometheus"). So according to https://docs.cloudfoundry.org/loggregator/log-ops-guide.html this causes the metrics to be split across instances. I was not aware of this, so giving each exporter a unique subscription id seems to fix the problem. The sample application had a different default subscription id and that's why it always received the full metrics.

I am not sure why `n.messages, n.errs = n.consumer.Firehose(n.subscriptionID, "")` also fixed the problem, but that would be an issue with noaa.

**Comment by andrewghobrial** [comment]
I would say it would be useful to have an option to have a randomly assigned subscription id. Otherwise, I have to deal with that externally if I have to run multiple instance of the exporter.

**Comment by frodenas** [comment]
Thanks @andrewghobrial for the heads up.

Out of curiosity, why do you want to have different subscription ids? if your prometheus instance is scrapping all `firehose_exporters`, then you will always get the data, even when using the same subscription id. Most of the rules and dashboards at the [prometheus-boshrelease](https://github.com/bosh-prometheus/prometheus-boshrelease) are already tunned to support multiple firehose instances.

**Comment by andrewghobrial** [comment]
I'm currently using the exporter directly without a prometheus instance to cache the firehose metrics for my app. Each instance of my app has its own exporter instance, so for me it makes sense for each exporter to be independent.

**Comment by frodenas** [comment]
Understood, thanks.
