### ISSUE TITLE
Firehose Exporter returns inconsistent number of values. 

### ISSUE THREAD

**Issue by abelnbcuni** [bosh-prometheus/firehose_exporter#32]
Hi, I am using the firehose exporter to gather information about capacity metrics in a PCF foundation. However i am getting an inconsistent number of values returned in queries. I am not sure if it something with the exporter or how i have set it up. 
![screenshot_2018-06-13 prometheus time series collection and processing server 1 1](https://user-images.githubusercontent.com/20228908/41609967-d0177676-73a0-11e8-8740-85dbd7b634ca.png)

**Comment by frodenas** [comment]
@abelnbcuni What's exactly the inconsistency? The number of samples?

**Comment by abelnbcuni** [comment]
@frodenas Yes it is the number of samples. The number of values should equal the number of diego cells. I believe the count of diego cells is not changing. However the firehose exporters returns different counts
