### ISSUE TITLE
Checking health of exporter

### ISSUE THREAD

**Issue by andrewghobrial** [bosh-prometheus/firehose_exporter#33]
Hi,

I notice that the exporter always gives 200 ok response regardless of it being able to connect successfully to firehose socket or any errors displaying in the console. Is there a way to detect exporter errors from http response?

**Comment by frodenas** [comment]
The exporter should fail if it cannot connect to the firehose when it's started or when the socket is closed. Have you observed a different behavior?

Another way to check if the exporter is not getting any message from the firehose is to check the latest received envelope timestamp metric. An example can be found at the [cloudfoundry alerts](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_alerts/templates/prometheus_firehose_exporter.alerts.yml#L14).

**Comment by andrewghobrial** [comment]
@frodenas thanks.

I created this command that can be used to create a liveness check:

`exit $(( ($(date +'%s') - $( wget localhost:9186/metrics -O - -q | grep ^firehose_last_envelope | sed -r 's/firehose_last_envelope_received_timestamp[^ ]* //' | xargs printf '%.0f\n' )) > 60 ))`

Ideally I would say the exporter should detect this and automatically try to reconnect again or kill itself
