### ISSUE TITLE
aggregate/link the appID with the CF org/space and app name

### ISSUE THREAD

**Issue by reneherrero** [bosh-prometheus/firehose_exporter#34]
Hi,
Wondering if anyone can give me pointers as to how I can aggregate/link the appID with the CF org/space and app name? Something tells me someone has gone through this before?
Thanks

**Comment by frodenas** [comment]
You need to use a [vector matching](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching) operator.

This [example](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_dashboards/templates/cf_services.json#L339) matches a `cf_service_binding_info` (where we only have the `application_id`) with the `cf_application_info` (where we have the `application_name`, `organization_name` and  `space_name`.

**Comment by reneherrero** [comment]
Thanks @frodenas and apologies for the slow response
