### ISSUE TITLE
Multiple instances of firehose exporter on different foundations suddenly stopped exposing metrics

### ISSUE THREAD

**Issue by timlharrison** [bosh-prometheus/firehose_exporter#37]
I have this exporter deployed on several PCF foundations and all but one of them suddenly stopped displaying firehose metrics at the same time - all exactly 30 days after first deploying the app.  There were no errors in the app's logs.  The exporters were still running and showing the go metrics, just not the firehose metrics.  Upon restart, all the metrics started working again on all of the exporters.

Gut feeling is it was some kind of token expiration issue.

**Comment by frodenas** [comment]
I've seen this before, but so far, I haven't determined yet the cause. Like you, I suspect a token refresh that went wrong.

**Comment by RMeharg** [comment]
I am also seeing this issue only with PCF 2.4, both deployed on CF and standalone after a few days.

**Comment by omkarphadke84** [comment]
Has anyone observed this on PCF v2.5?

**Comment by pusherofbrooms** [comment]
We see a similar symptom in all of our AWS based deployments. In our case, time between starting the exporter and the metrics disappearing is not fixed.

What seems to be happening in our deployments is that the firehose exporter keeps the socket open to a particular ELB IP address long after the ELB has sent its hangup and changed IP addresses. We restart the exporter and it connects to one of the active IP addresses for the ELB and metrics are again exported.
