### ISSUE TITLE
Invalide metric type

### ISSUE THREAD

**Issue by ntdt** [bosh-prometheus/firehose_exporter#38]
Dear all,

With prometheus-boshrelease v23.3.0, we have an error on
`invalid metric type "_kyu_9_jt_tug_3_l_369_i_92_jjg_consumers gauge" `
and /metrics return
`# TYPE firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_7_dd_8_ba_19_229_d_4_a_4_f_9_dce_4416_fbb_728_ff_spring_cloud_hystrix_stream_anonymous_._kyu_9_jt_tug_3_l_369_i_92_jjg_consumers gauge`

**Comment by ntdt** [comment]
IMO, this error is related to prometheus it-self. So the metrics is not parsed by prometheus. I wonder if this bug is related? https://github.com/prometheus/prometheus/issues/4602

**Comment by simonpasquier** [comment]
It looks like there is a dot in the metric name which is invalid for Prometheus (valid names match `[a-zA-Z_:][a-zA-Z0-9_:]*`), see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels.

**Comment by ywei2017** [comment]
Any update on this. I have the same issue impacting multiple environments. All needed is a sanitization rule to replace '.' with '_'. I can put in a P/R if that is an acceptable fix.

**Comment by robplahn** [comment]
@ywei2017 I have opened a support case with Pivotal and escalated it (#194725).  So far I have not received any answers. To work around this problem I have modified the firehose_exporter using the 'deployment_filter' flag to drop the rabbitmq related metrics.  I would love to see your PR on this if you have worked out how to sanitize the illegal use of the '.' and also please include '-' which is also not allowed in the metric name.  My example is below. Thanks for keeping this issue active.  
# TYPE firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_0_b_5082_d_6_3612_40_b_8_8_eed_fca_56661_b_74_d_stomp_subscription_-_caz_cnr_uk_9_g_8_nv_e_7_xr_dw_consumers gauge

**Comment by robplahn** [comment]
@ywei2017 @frodenas @mevansam There is an old PR that was merged for what seems like a very similar issue with '/' back in 2016 and we are now having with '.' and '-' characters. 
https://github.com/bosh-prometheus/firehose_exporter/pull/2/files
I'm not a go programmer, but it appears that perhaps this utils/normalize_name.go is supposed to sanitize the names against the regex.  
https://github.com/bosh-prometheus/firehose_exporter/blob/master/utils/normalize_name.go

**Comment by ywei2017** [comment]
@robplahn @frodenas I took some time looking through the code, and have a hard time to understand everything. in [normalize_name.go](https://github.com/bosh-prometheus/firehose_exporter/blob/master/utils/normalize_name.go), it seems the name has been normalized and any '.' should be replaced with '_', so I don't know any of them could have escaped. I must admit that I don't understand a large part of the code structure.

**Comment by ywei2017** [comment]
An update. I tried and failed to recreate the problem.
- I tried with newly built binary from the source, and the binary from R23.4.0
- Then I created a rabbitmq instance, an a few queues including '.' in the name.

In both cases, all the "." are replaced with "_". I have no doubt there is a problem, but deeper than it looks. The queue must be named in a really weird way to trigger it.

**Comment by frodenas** [comment]
This should be fixed at https://github.com/bosh-prometheus/firehose_exporter/commit/be93e2668f89ce2dd5d9c863748359966bd6f880. I'll cut a new relase soon.

**Comment by frodenas** [comment]
[v5.0.4](https://github.com/bosh-prometheus/firehose_exporter/releases/tag/v5.0.4) fixes this issue.

**Comment by ywei2017** [comment]
@frodenas Most wonderful, thank you very much for the quick action. Was scratching my head last night when I went to sleep, wondering "what can I do". Thank you very much.

**Comment by robplahn** [comment]
@frodenas Thanks for the fix!  Looking forward to testing it.  Just to be clear our problem was with the '-' character not '.' but I am hopeful your fix would address that at well.  Using the regex in the normalize_name.go, '[^a-zA-Z0-9_]*$' I get a full match on the following example. 
``TYPE firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_0_b_5082_d_6_3612_40_b_8_8_eed_fca_56661_b_74_d_stomp_subscription_-_caz_cnr_uk_9_g_8_nv_e_7_xr_dw_consumers``
I will post an update after testing.

**Comment by frodenas** [comment]
The fix should fix both characters (`-` and `.`).

**Comment by ywei2017** [comment]
@frodenas, will you issue a new Prometheus release including this fix?

Thanks 
Yansheng

**Comment by frodenas** [comment]
This weekend most likely.

**Comment by ywei2017** [comment]
That is fantastic
