### ISSUE TITLE
No RabbitMQ metrics after PCF upgrade

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/firehose_exporter#39]
_BOSH Director 2.2-build.372
Pivotal Application Service 2.2.9
RabbitMQ 1.13.11
Spring Cloud Services 1.5.6
MySQL for PCF 1.10.14_
was updated and now firehose_value_metric_p_rabbitmq_* metrcis are gone
firehose_exporter works ok but there are no metrics only from rabbitmq
logs are empty

**Comment by Alexvianet** [comment]
@frodenas we have 4 environments and it happened on all of them after  PCF upgrade =(

**Comment by mkuratczyk** [comment]
Hey. Can you check with `cf nozzle` if the metrics are in the firehose or not? If not, there is nothing the exporter could do about that and it's a problem with the RabbitMQ tile. I'm a member of the RabbitMQ tile R&D team - you can ping me on Slack or you can raise a support case with Pivotal if you don't have the expected metrics in the firehose.

Best regards,

**Comment by Alexvianet** [comment]
thanks i ll check

**Comment by Alexvianet** [comment]
@mkuratczyk what is the slack workspace?

**Comment by mkuratczyk** [comment]
Please join https://slack.cloudfoundry.org/.

**Comment by Alexvianet** [comment]
rabbitmq fail with service-metrics log: 
{"timestamp":"1544522600.982705593","source":"service-metrics","message":"service-metrics.Error while flushing: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for metron_tls_cert, not metron\"","log_level":1,"data":{}}
