### ISSUE TITLE
Firehose exporter stopped exporting metrics 

### ISSUE THREAD

**Issue by vinit134** [bosh-prometheus/firehose_exporter#40]
We deployed firehose-exporter v5.0.3  on 7 foundations and  suddenly it stopped exporting the metrics but app it self up and running. We faced this issue on all foundations but not in any fixed patterns. 
While debugging I found huge consumption of CPU and memory before it stopped exporting. 
If I restart the firehose app then again it started exporting metrics. 

screenshot of usage. 
![image](https://user-images.githubusercontent.com/12510864/51307760-c5300b00-1a40-11e9-8b75-7b382c4099f4.png)

Could you please help me in troubleshooting?

**Comment by rorynelsonscott** [comment]
We run into the same issue sporadically but haven't found a good solution yet.

**Comment by frodenas** [comment]
Closing in favor of #37 (which was opened first).
