### ISSUE TITLE
Why firehose_http_start_stop_requests is not a counter?

### ISSUE THREAD

**Issue by prolane** [bosh-prometheus/firehose_exporter#41]
Hi,

As you've seen in the [prometheus-boshrelease](https://github.com/bosh-prometheus/prometheus-boshrelease/issues/276) issues, I'm currently trying to get the apps request per second metrics right.

In short, I propose to change this prometheus query (used in a Grafana dashboard) from this:
```
avg(rate(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}[5m]))
```

to this:
```
sum(firehose_http_start_stop_requests{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})/300
```

This already takes this graph closer to reality. However, I kept thinking about this `firehose_http_start_stop_requests` metric coming from `firehose_exporter`. There is just something I don't understand.

The [FAQ](https://github.com/bosh-prometheus/firehose_exporter/blob/76b9c9fd1d4a3b1dbc900072d375cbf2a71e13e8/FAQ.md) says this:
`The exporter summarizes applications related HTTP requests from a slidding window (doppler.metric-expiration command flag) from the Cloud Foundry Firehose and emits ....`

I suppose with more knowledge about the CF Firehose behaviour this sentence could make sense, but for people like myself (and I'm sure other people) its hard to understand what this means. I can explain what I see happening though: When I send 1 request to an app, I'll see the `firehose_http_start_stop_requests` metric increase with 1 for this particular app. So far so good. But then after the `doppler.metric-expiration` time, the metric will decrease by 1.

What I'd like to understand is why this behaviour is implemented like this. Because in my mind these `http_start_stop_requests` events would be a typical use case for a `counter` metric. This would make the querying of the metric in Prometheus a lot more straightforward.

Because to be honest, I see the above `sum(firehose_http_start_stop_requests{label=value})/300` solution more to be a workaround.

Would you care to explain?

**Comment by frodenas** [comment]
Because this exporter is just a proxy that converts metrics from firehose envelopes to prometheus metrics. As those two models are completely different (firehose emits events and prometheus uses a pull model), the exporter just tries to its best by keeping some data from the firehose until prometheus scrapes it or the data expires according to the window times.

In the case of `http_start_stop` metrics, the problem is that the firehose only emits them when there's a request on an application, and it just emit an event, not a counter. As the exporter does not store previous data (besides the slidding window), there's no way to report it as a counter, or if we report it as a counter, you will see that arbitrarily will go up and down, which in fact, is a gauge.

Hope this helps, feel free to drop me more questions if it's not yet clear.

**Comment by prolane** [comment]
Yes, this helps to understand. Thanks @frodenas
Then I think it should be fine if we set `doppler.metric-expiration` to a lower number, like 2 minutes for example. As long as the prometheus scrape rate is lower than the `doppler.metric-expiration`, right? This would make the resolution a bit better (i.e. show RPS averaged over a 2 minute time window, instead of a 5 minute time window).

I understand since you want the firehose_exporter to just be a proxy and not store state, you had to come up with something. I'm just wondering if having a counter wouldn't have been easier?

Here are my thoughts:
Now you need to store state for every http request for the duration of the `metric-expiration` setting. That is, you need to keep track for how long each http request has been emitting.

But what if you would only keep state for every unique combination of `application_id,bosh_deployment,environment,host,instance_id,method,scheme,status_code`? I think in the end you're keeping track of less items. And it does not need to be persistent state. If the firehose_exporter dies or needs to be restarted, the counters can just start from zero. Prometheus is can very well deal with these counter resets.

Food for thoughts perhaps? Anyway, I'm not trying to push you towards anything. I just thought it would be interesting to discuss this with you.
