### ISSUE TITLE
The process misses to export all firehose tags keys 

### ISSUE THREAD

**Issue by jointcloudfoundry** [bosh-prometheus/firehose_exporter#42]
We are using some metrics customization on the messsages sent to firehose (with tags Keys) . We can see those tags in the firehose (with cf nozzle) , but they are lost on the firehose exporter end point .
Those tags contain ApplicationId and AppInstance ID , so that it's possible to retrieve custom metrics in Prometheus for instance .
Those tags are standard regarding the documentation (https://github.com/cloudfoundry/dropsonde-protocol/blob/master/events/README.md) , so it's important that we can get them .
Thanks

**Comment by frodenas** [comment]
Glad to accept a contribution with those changes :) Bear in mind that labels in prometheus must be consistent on all metrics from a particular family, so this means that all events of the same type should have the same tags, or you will need to implement some logic at the exporter to deal with this.

**Comment by mathias-ewald** [comment]
I think I have identified the place in the code where the tags get lost. I will try to figure out a PR.

**Comment by mathias-ewald** [comment]
@jointcloudfoundry I just tested the patch in the above mentioned pull request and it worked for me. Can you give feedback, if the behavior is now what you expect?

**Comment by erboucherie** [comment]
Hello mathias . I've just tested your patch (pushing to cloudfoundry the app from your repo https://github.com/mathias-ewald/firehose_exporter.git , on the right branch)
I confirm that this solve the issue above . We can see all the tags in the output of firehose-exporter .

**Comment by mathias-ewald** [comment]
That's awesome! Now we need to wait for a reviewer to accept the PR, I guess :) @frodenas
