### ISSUE TITLE
Application CounterEvent metrics are not splitted over the application instances

### ISSUE THREAD

**Issue by jointcloudfoundry** [bosh-prometheus/firehose_exporter#45]
We are using **firehose-exporter** as a single endpoint to scrape all in one application and system metrics from the firehose . Unfortunately for application metrics , we can only see the **ValueMetric** for individual instances . For **CounterEvent** we have one uniq metric which does not even represent the aggregation of all the instances of a particular application . 
In the firehose we see them (cf nozzle -f CounterEvent) . So as a firehose proxy , i would expect to see the same metrics in firehose-exporter .
Thanks to answer if it's an improvement or an issue .

**Comment by bens473** [comment]
Having this same problem. Any updates?
