### ISSUE TITLE
firehose-exporter is missing in depth heap data ( Survivor Space, Eden Space, Metaspace etc)

### ISSUE THREAD

**Issue by jointcloudfoundry** [bosh-prometheus/firehose_exporter#47]
Hi,
We want to use firehose-exporter to get some customize heap data, but it exposes only tenured gen data and drops rest others like,
1. File Descriptors
2. Heap:- Eden Space, Survivor Space
3. Non-Heap:- Metaspace, Compressed Class Space, Code Cache
4. Garbage Collection:- Collections, Pause Durations, Allocated/Promoted 

Firehose-exporter output:- 
`# TYPE firehose_value_metric_9629_bd_8_a_d_499_47_c_6_9063_1190_b_4_e_27472_jvm_memory_used_bytes gauge
firehose_value_metric_9629_bd_8_a_d_499_47_c_6_9063_1190_b_4_e_27472_jvm_memory_used_bytes{application_guid="9629bd8a-d499-47c6-9063-1190b4e27472",application_instance="1",area="heap",bosh_deployment="cf-831082f4cc611c010e5c",bosh_job_id="d11159c1-aefd-4ca7-a4fd-3e552828bfe0",bosh_job_ip="172.21.220.56",bosh_job_name="doppler",environment="AMS-NONPROD",id="Tenured Gen",instance_id="1",origin="9629bd8a-d499-47c6-9063-1190b4e27472",product="Pivotal Application Service",source_id="9629bd8a-d499-47c6-9063-1190b4e27472",system_domain="sys-ta-ams.af-klm.com",unit=""} 3.8100416e+07
`
We deployed[ promregator](https://github.com/promregator/promregator) and all the above missing data are already there. 
`# TYPE jvm_memory_used_bytes gauge
jvm_memory_used_bytes{area="nonheap",id="Code Cache",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 3.029344E7
jvm_memory_used_bytes{area="nonheap",id="Metaspace",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 5.7728192E7
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 6894560.0
jvm_memory_used_bytes{area="heap",id="Eden Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 1.4957776E7
jvm_memory_used_bytes{area="heap",id="Survivor Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 746672.0
jvm_memory_used_bytes{area="heap",id="Tenured Gen",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:0",cf_instance_number="0",} 3.7933536E7
jvm_memory_used_bytes{area="nonheap",id="Code Cache",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 3.0955456E7
jvm_memory_used_bytes{area="nonheap",id="Metaspace",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 5.7782856E7
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 6912616.0
jvm_memory_used_bytes{area="heap",id="Eden Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 1.9109648E7
jvm_memory_used_bytes{area="heap",id="Survivor Space",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 708144.0
jvm_memory_used_bytes{area="heap",id="Tenured Gen",org_name="PTOPT",space_name="default",app_name="afterburner",cf_instance_id="9629bd8a-d499-47c6-9063-1190b4e27472:1",cf_instance_number="1",} 3.8100416E7`
 
Could you please help us to fix this issue?

Thanks.

**Comment by faisaltheparttimecoder** [comment]
@frodenas If you can have a look at the pull request https://github.com/bosh-prometheus/firehose_exporter/pull/48
