### ISSUE TITLE
"discarded: duplicate label names" errors in the log 

### ISSUE THREAD

**Issue by ibmdcb** [bosh-prometheus/firehose_exporter#59]
When I run logs -f firehose-exporter-0, I see the following entries for every prometheus pull. Resulting in large volume of logs.

Can I suppress them? Should this be logged at warning? Also what caused the duplicate labels?

Greatly appreciated for any insights.

time="2020-08-26T15:17:18Z" level=error msg="Value Metric `http_request_seconds_sum` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `retention_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `shard_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `egress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `http_request_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `egress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `average_envelopes` from `loggregator.metron` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `queue_disk_usage` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `http_request_seconds_sum` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `egress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `http_request_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `queue_disk_usage` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `retention_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `average_envelopes` from `loggregator.metron` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:18Z" level=error msg="Value Metric `egress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `shard_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `retention_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `egress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `queue_disk_usage` from `log_store.nozzle` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `egress_connection_count` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `ingress_connection_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `queue_disk_usage` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `shard_count` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `http_request_seconds_sum` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `average_envelopes` from `loggregator.metron` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `http_request_seconds` from `log_store.log_store` discarded: duplicate label names" source="value_metrics_collector.go:65"
time="2020-08-26T15:17:19Z" level=error msg="Value Metric `queue_disk_usage` from `log_store.router` discarded: duplicate label names" source="value_metrics_collector.go:65"

**Comment by daviddob** [comment]
This is due to the fact that the metrics coming from appMetrics log_store are not being sent with the proper `valueMetric.Unit` and instead are sending the unit in the tags. This causes prometheus to discard the tag as when the collector builds the metric it has two tags for `unit` - one that is a const label that should come from `valueMetric.Unit` and the other coming from additional tags from log_store

A fix can be found here - though it only solves the case where unit is set in tags and not the general case of duplicate tags. https://github.com/dickssportinggoods/firehose_exporter/commit/cfd2f20c15122db25ce0205839bd7e476cd74fe6
