### ISSUE TITLE
Counter Event Labels Have Double Underscore

### ISSUE THREAD

**Issue by timlharrison** [bosh-prometheus/firehose_exporter#61]
I upgraded to 6.2.0 in my sandbox environment and found that with the recent change to counter events, my counter event label values have a double underscore between "counter_event" and the counter. I am seeing this on both _total and _delta counters. See example below:

firehose_counter_event__failed_scrapes_total{bosh_deployment="cf-xxxxxxxxxx",bosh_job_id="xxxxxxx",bosh_job_ip="xx.xx.xx.xx",bosh_job_name="diego_cell",environment="pcf",instance_id="xxxxxxxx",origin="",product="VMware Tanzu Application Service",scrape_source_id="syslog_agent",source_id="metrics-agent",system_domain="system.pcf.domain.local"} 0

This is on VMware TAS 2.10.9

**Comment by frodenas** [comment]
Thanks for reporting this @timlharrison. I checked my environment and I'm seeing the same, the problem is that the firehose is not sending the `origin` label (hence the double underscore, the origin label should be between the underscores). I still need to investigate what's going on.

**Comment by timlharrison** [comment]
FYI, this issue appears to be present in 6.0.0 as well... I guess I just never noticed it before.
