### ISSUE TITLE
value metric origin difficult to use

### ISSUE THREAD

**Issue by zcavaliero** [bosh-prometheus/firehose_exporter#62]
I've found that the value metrics like this: firehose_value_metric_ded_d_e_e_5_d_deb_4_4_f_92_85_f_2_2_fe_3_ae_4_b_6_e_23_jvm_memory_committed_bytes
make it difficult to query in prometheus and I was wondering if there is a setting to omit the origin guid or if anyone has suggestions on ways to make it easier to query prometheus without needing to know the whole application guid

Thanks,

Zac

**Comment by daviddob** [comment]
There is currently a WIP implementation for this here if you are interested - it needs to be cleaned up a bit and variablize out the preferred replacement origin for guid based metrics. 

https://github.com/dickssportinggoods/firehose_exporter/commit/64fd5f2e92681057a2e27916bc7b4834f51548c7
