### ISSUE TITLE
The bosh_deployment tag appears to be missing from some metrics

### ISSUE THREAD

**Issue by amhuber** [bosh-prometheus/firehose_exporter#87]
This is breaking the HTTP related CF dashboards per https://github.com/bosh-prometheus/prometheus-boshrelease/issues/480.  These ones specifically are impacted but there may be others:

firehose_http_total
firehose_http_duration_seconds_sum

**Comment by amhuber** [comment]
Stale because no one has fixed it, still broken.

**Comment by amhuber** [comment]
Still broken...

**Comment by benjaminguttmann-avtq** [comment]
Problems seems to be here that those internal metrics https://github.com/bosh-prometheus/firehose_exporter/blob/7fdf4439a6d79efc87833fc9106205b59a0861b0/metrics/internal_metrics.go#L8 do not differentiate between different bosh_deployments as of know.
